### ISSUE TITLE
Different syntax highlighting theme for nightmode.

### ISSUE THREAD

**Issue by NiamhFerns** [Jwrede/Anki-KaTeX-Markdown#36]
It's pretty easy to change the background colour so that the syntax highlighting is visible in dark mode, but it's still clear that the actual highlighting being used on the text itself is intended for a light mode background (dark greens, reds, etc). 

It's not a major thing, but is it possible to change this?

I've tried replacing the _highlight.css file with one of a different theme from the https://highlightjs.org/download/ website. This doesn't change anything however.

**Comment by renercrisostomo** [comment]
Add

```CSS
.nightMode pre code {
	color: black;
	filter: invert(1) hue-rotate(180deg);
}
.mobile .night_mode pre code {
	color: white;
	filter: invert(0) hue-rotate(0deg);
}
```

on line 604 in HTMLandCSS.py

![image](https://user-images.githubusercontent.com/91918580/202874871-2f7e4854-5ea0-47b0-9f96-f2248d2b6942.png)

Desktop and AnkiDroid:
![image](https://user-images.githubusercontent.com/91918580/202875199-db8f80f0-e8ab-4ca3-a96a-49e75909f7fc.png)
